spring:
  application:
    name: hhplus_ecommerce
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    defer-datasource-initialization: true

#logging:
#  level:
#    org.hibernate.SQL: debug

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html