spring:
  config:
    activate:
      on-profile: local

  redis:
    host: localhost
    port: 6379
    password: 1234

  application:
    name: hhplus_ecommerce
  datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb:~/h2db
        username: sa
        password:
    #    url: jdbc:h2:mem:testdb:tcp://localhost/~/h2db
    #    url: jdbc:h2:mem:testdb:~/h2db;AUTO_SERVER=true

#    url: jdbc:h2:~/h2db
#    url: jdbc:h2:tcp://localhost/~/h2db


  h2:
    console:
      enabled: 'true'