spring:
  profiles:
    active: local

  application:
    name: hhplus_ecommerce

  h2:
    console:
      enabled: 'true'

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    database: mysql
    properties:
      hibernate:
        ddl-auto: create-drop
        #        globally_quoted_identifiers: true
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html