spring:
  redis:
    host: localhost
    port: 6379
    password: 1234
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: 'true'